spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/speedrweb_dev
    username: enesgunumdogdu
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

speedrweb:
  storage:
    video-dir: ./uploads/videos-dev
  jwt:
    secret: speedrweb-dev-jwt-secret-key-do-not-use-in-production-1234567890

logging:
  level:
    com.speedrweb: DEBUG
    org.springframework.web: DEBUG
